[32mINFO    [0m pytest_operator.plugin:plugin.py:806 Connecting to existing model github-pr-4f6bd-microk8s:testing on unspecified cloud
[32mINFO    [0m juju.model:model.py:2631 Waiting for model:
  test (missing)
[32mINFO    [0m juju.model:model.py:1994 Deploying local:jammy/test-upload-0
[32mINFO    [0m juju.model:model.py:2631 Waiting for model:
  test/0 [idle] active:
[32mINFO    [0m pytest_operator.plugin:plugin.py:951 Model status:

Model    Controller                Cloud/Region        Version  SLA          Timestamp
testing  github-pr-4f6bd-microk8s  microk8s/localhost  2.9.52   unsupported  11:04:15Z

App   Version  Status  Scale  Charm        Channel  Rev  Address        Exposed  Message
test           active      1  test-upload             0  10.152.183.99  no       

Unit     Workload  Agent  Address     Ports  Message
test/0*  active    idle   10.1.53.10         


[32mINFO    [0m pytest_operator.plugin:plugin.py:957 Juju error logs:


[32mINFO    [0m pytest_operator.plugin:plugin.py:1039 Forgetting model main...
[31m[1mERROR   [0m websockets.client:protocol.py:1009 data transfer failed
Traceback (most recent call last):
  File "/home/ubuntu/actions-runner/_work/operator-workflows/operator-workflows/tests/workflows/integration/test-upload-charm/.tox/integration/lib/python3.12/site-packages/websockets/legacy/protocol.py", line 953, in transfer_data
    message = await self.read_message()
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/actions-runner/_work/operator-workflows/operator-workflows/tests/workflows/integration/test-upload-charm/.tox/integration/lib/python3.12/site-packages/websockets/legacy/protocol.py", line 1023, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/actions-runner/_work/operator-workflows/operator-workflows/tests/workflows/integration/test-upload-charm/.tox/integration/lib/python3.12/site-packages/websockets/legacy/protocol.py", line 1098, in read_data_frame
    frame = await self.read_frame(max_size)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/actions-runner/_work/operator-workflows/operator-workflows/tests/workflows/integration/test-upload-charm/.tox/integration/lib/python3.12/site-packages/websockets/legacy/protocol.py", line 1155, in read_frame
    frame = await Frame.read(
            ^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/actions-runner/_work/operator-workflows/operator-workflows/tests/workflows/integration/test-upload-charm/.tox/integration/lib/python3.12/site-packages/websockets/legacy/framing.py", line 70, in read
    data = await reader(2)
           ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/streams.py", line 752, in readexactly
    await self._wait_for_data('readexactly')
  File "/usr/lib/python3.12/asyncio/streams.py", line 545, in _wait_for_data
    await self._waiter
  File "/usr/lib/python3.12/asyncio/selector_events.py", line 1075, in write
    n = self._sock.send(data)
        ^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 9] Bad file descriptor
[33mWARNING [0m juju.client.connection:connection.py:543 Receiver: Connection closed, reconnecting